; O3 Ozone Project.
; O3 programing language.
; file generated by X64Halogen.
; 2020-09-12 18:27:48
bits 64

extern _o3prtStr
extern _o3prtDouble
extern _o3prtFloat
extern _o3prtInt
extern _o3prtStrLn
extern _o3prtDoubleLn
extern _o3prtFloatLn
extern _o3prtIntLn
extern _o3upperCase
extern _o3lowerCase
extern _o3camelCase
extern _o3pascalCase
extern _o3snakeCase
extern _o3kebabCase
extern _o3reverseCase
extern _o3ltrim
extern _o3rtrim
extern _o3trim

section .data
	main_val1:  dq  10.0
	main_val2:  dd  5
	main_val3:  dq  5.0

section .bss

section .text
	global _main

_main:

	push  rbp
	mov   rbp, rsp
	
	movsd xmm0, [rel main_val3]
	call _o3prtDoubleLn

	mov   rax, 0x02000001
	xor   rdi, rdi
	syscall
