; O3 Ozone Project.
; O3 programing language.
; file generated by X64Halogen.
; 2020-08-31 22:50:10
bits 64

extern _o3prtStr
extern _o3prtDouble
extern _o3prtFloat
extern _o3prtInt
extern _o3prtStrLn
extern _o3prtDoubleLn
extern _o3prtFloatLn
extern _o3prtIntLn
extern _o3upperCase
extern _o3lowerCase
extern _o3camelCase
extern _o3pascalCase
extern _o3snakeCase
extern _o3kebabCase
extern _o3reverseCase

section .data
	main_text:  db  "Hello World!!!" , 0x0

section .text
	global _main

_main:

	push      rbp
	mov       rbp, rsp	

	rdi, main_text
	call _o3upperCase

	mov     rax, 0x02000001
	xor     rdi, rdi
	syscall
