; O3 Ozone Project.
; O3 programing language.
; file generated by X64Halogen.
; 2020-08-29 23:32:15
bits 64

extern _o3prtStr
extern _o3prtDouble
extern _o3prtFloat
extern _o3prtInt
extern _o3prtStrLn
extern _o3prtDoubleLn
extern _o3prtFloatLn
extern _o3prtIntLn
extern _o3upperCase
extern _o3lowerCase
extern _o3camelCase
extern _o3pascalCase
extern _o3snakeCase
extern _o3kebabCase
extern _o3reverseCase

section .data
	main_pi:  dd  3.1415927
	main_text:  db  "Hello World!!!" , 0x0
	main_labelPi:  db  "Pi: " , 0x0
	main_money:  dq  3.141592653589793
	main_labelMoney:  db  "Money: " , 0x0

section .text
	global _main

_main:

	push      rbp
	mov       rbp, rsp	

	mov rdi, main_text
	call _o3prtStrLn


	mov rdi, main_labelMoney
	call _o3prtStr


	movsd xmm0, [rel main_money]
	call _o3prtDoubleLn


	mov rdi, main_labelPi
	call _o3prtStr


	movss xmm0, [rel main_pi]
	call _o3prtFloatLn

	mov     rax, 0x02000001
	xor     rdi, rdi
	syscall
